//  const styles = {
//     container: {
//       backgroundColor: "#f2f2f2",
//       minHeight: "100vh",
//       padding: "20px",
//       display: "flex",
//       justifyContent: "center",
//     },
//     cartBox: {
//       backgroundColor: "#fff",
//       borderRadius: "8px",
//       width: "80%",
//       maxWidth: "800px",
//       overflow: "hidden",
//     },
//     header: {
//       backgroundColor: "#e6e6e6",
//       padding: "15px",
//       fontWeight: "bold",
//     },
//     tableHeader: {
//       display: "flex",
//       justifyContent: "space-between",
//       padding: "10px 20px",
//       borderBottom: "1px solid #ccc",
//       fontWeight: "bold",
//     },
//     productRow: {
//       display: "flex",
//       justifyContent: "space-between",
//       alignItems: "center",
//       padding: "15px 20px",
//       borderBottom: "1px solid #eee",
//     },
//     productInfo: {
//       display: "flex",
//       alignItems: "center",
//       gap: "15px",
//     },
//     productImage: {
//       width: "50px",
//       height: "50px",
//       objectFit: "cover",
//       borderRadius: "5px",
//       backgroundColor: "#f0f0f0",
//     },
//     qtyBox: {
//       display: "flex",
//       alignItems: "center",
//       gap: "5px",
//     },
//     qtyButton: {
//       width: "25px",
//       height: "25px",
//       textAlign: "center",
//       border: "1px solid #ccc",
//       backgroundColor: "#fff",
//       cursor: "pointer",
//     },
//     summary: {
//       display: "flex",
//       justifyContent: "space-between",
//       alignItems: "center",
//       padding: "20px",
//     },
//     payButton: {
//       backgroundColor: "#ffb300",
//       color: "#000",
//       border: "none",
//       padding: "10px 25px",
//       fontWeight: "bold",
//       borderRadius: "5px",
//       cursor: "pointer",
//       display: "flex",
//       alignItems: "center",
//       gap: "5px",
//     },
//   };

// export default styles